/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_skymxc_lesson_41_jni_demo_TestJni */

#ifndef _Included_com_skymxc_lesson_41_jni_demo_TestJni
#define _Included_com_skymxc_lesson_41_jni_demo_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_skymxc_lesson_41_jni_demo_TestJni
 * Method:    jniAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_skymxc_lesson_141_1jni_1demo_TestJni_jniAdd
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
